spring:
  datasource:
    url: jdbc:mysql://localhost:3306/noticiero?serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: 042577
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create #le decimos q se haga cargo de la cleacion de las tablas